POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e489df7e-079a-4c7b-97bc-fbfb81ba560c"    
}


###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "d3752577-50dd-4fbf-9bdd-23b3ceaa0523"    
}